---
title: 'DataVis 599 B: TabularData Bivariate Homework'
author: 'Group 4: Haotian Bu, Aishe Memetova, Jon White, Vitalii Zakhozhyi'
output:
  html_document:
    df_print: paged
  pdf_document: default
---

Using the Seattle Sound Transit Data of October-November 2015, we will try to answer what type of fare is the most common given different purpose of trips.

**Loading neccessary packages, calling dataset and preparing it for analysis**


```{r linkdata}
library(ggplot2)
library(magrittr)
library(scales)
library(dplyr)

linkdata <- read.csv("https://raw.githubusercontent.com/jwhite00/Group-Project-Data-Vis/master/Data/newLinkData.csv", stringsAsFactors=FALSE)
```

**Cleaning the data and creating the proportion table**

```{r linkdataclean}
linkdata_clean <- linkdata %>%
  filter(faretype != "#NULL!") %>%
  filter(purpose != "#NULL!")

linkincomefare=table(linkdata_clean$faretype, linkdata_clean$purpose)%>%
         prop.table(margin = 2)%>%   # 2 is % by column
         "*"(100)%>%
         round(3)
```

**Creating the dataframe for building the plot**

```{r dflink}
dflink=as.data.frame(linkincomefare)
names(dflink)=c('Fairtype','Purpose','Percent')
dflink_new = dflink %>% 
  mutate(Fairtype = recode(Fairtype, 'FALSE' = "Other")) #recoding FALSE to Other, meaning other type of fare
```

**Building the plot**

```{r barplotfarepurpose}
base  = ggplot(dflink_new, aes(x = reorder(Fairtype, Percent), y = Percent))
bars1 = base + geom_bar(stat = "identity")
bars2 = bars1 + facet_wrap( ~ Purpose ,nrow = 1)
bars3 = bars2 + coord_flip() + 
                scale_y_continuous(limits=c(0,80),
                                  labels=scales::unit_format(suffix = '%'))
bars4 = bars3 + geom_text(aes(y = Percent,
                                  label = paste0(round(Percent,1), '%')), 
                                  hjust= -0.15, 
                                  size = 2.5)
bars5 = bars4 + labs(title='What fare type is the most common given different purpose of trips?',
                     x ='Fare type',
                     caption = 'Source: Seattle Open Data Portal')
bars6 = bars5 + theme(axis.text.y = element_text(size=8, angle = 30),
                      axis.text.x = element_text(size=7),
                      plot.title = element_text(size = 12, hjust = 0.5),
                      plot.caption = element_text(hjust = 1, vjust = -1.2),
                      axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.75),
                      axis.title.x = element_text(size = 11, hjust = 0.5, vjust = -1.25))
bars6
```



